In [52]:
import numpy as np#imports
import math as m

In [53]:
x1=1 #colculation of ortogeniel matrix for moments
y1=1
z1=-1
invek = np.array([x1,y1,z1])
ans = np.zeros([3,3])
if z1==0 and x1==0:
    ans = np.array([[1,0,0],[0,1,0],[0,0,1]])
elif z1>0:
    ans[0]=invek
    ans[1][0]=1
    ans[1][2]=-x1/z1*ans[1][0]
    if x1==0:
        ans[1]=[1,0,0]
    ans[2][2]=-1
    ans[2][0]=-ans[1][2]*ans[2][2]/ans[1][0]
    ans[2][1]=-(ans[2][0]*x1+ans[2][2]*z1)/y1
elif z1<0:
    ans[0]=invek
    ans[1][0]=-1
    ans[1][2]=-x1/z1*ans[1][0]
    if x1==0:
        ans[1]=[-1,0,0]
    ans[2][2]=1
    ans[2][0]=-ans[1][2]*ans[2][2]/ans[1][0]
    ans[2][1]=-(ans[2][0]*x1+ans[2][2]*z1)/y1
elif z1==0:
    ans[0]=invek
    if x1>0:
        ans[1]=[0,0,-1]
        ans[2][0]=-1
    else:
        ans[1]=[0,0,1]
        ans[2][0]=1
    ans[2][1]=-ans[2][0]*x1/y1
    
print(invek)
ans   

[ 1  1 -1]


array([[ 1.,  1., -1.],
       [-1.,  0., -1.],
       [-1.,  2.,  1.]])

In [54]:
import numpy.linalg as la #ortonormalization
ansNorm=np.array([ans[0]/la.norm(ans[0]),ans[1]/la.norm(ans[1]),ans[2]/la.norm(ans[2])])
ansNorm

array([[ 0.57735027,  0.57735027, -0.57735027],
       [-0.70710678,  0.        , -0.70710678],
       [-0.40824829,  0.81649658,  0.40824829]])

In [57]:
fi1=90/math.pi #delta colc
fi2=0
l1=2
l2=1

xp=l1*m.cos(fi1)*m.sin(fi2)
yp=l1*m.sin(fi1)
zp=l1*m.cos(fi1)*m.cos(fi2)

xbox=-l2*m.cos(fi1)*m.sin(fi2)
ybox=-l2*m.sin(fi1)
zbox=-l2*m.cos(fi1)*m.cos(fi2)

w1=0.2
w2=0.1

vxp=-w1*l1*m.sin(fi1)*m.sin(fi2)+w2*l1*m.cos(fi1)*m.cos(fi2)
vyp=w1*l1*m.cos(fi1)
vzp=-w1*l1*m.sin(fi1)*m.cos(fi2)-w2*l1*m.cos(fi1)*m.sin(fi2)

vxbox=-(-w1*l2*m.sin(fi1)*m.sin(fi2)+w2*l2*m.cos(fi1)*m.cos(fi2))
vybox=-(w1*l2*m.cos(fi1))
vzbox=-(-w1*l2*m.sin(fi1)*m.cos(fi2)-w2*l2*m.cos(fi1)*m.sin(fi2))

In [ ]:
cm = np.zeros(3) #abs colc
vcm = np.zeros(3)

corPar=np.zeros(3)
velPar=np.zeros(3)
corBox=np.zeros(3)
velBox=np.zeros(3)

corPar[0]=cm[0]+xp
corPar[1]=cm[1]+yp
corPar[2]=cm[2]+zp

corBox[0]=cm[0]+xbox
corBox[1]=cm[1]+ybox
corBox[2]=cm[2]+zbox

velPar[0]=vcm[0]+vxp
velPar[1]=vcm[1]+vyp
velPar[2]=vcm[2]+vzp

velBox[0]=vcm[0]+vxbox
velBox[1]=vcm[1]+vybox
velBox[2]=vcm[2]+vzbox